x-superset-user: &superset-user root
x-superset-volumes: &superset-volumes
  # /app/pythonpath_docker will be appended to the PYTHONPATH in the final container
  - ./docker:/app/docker
  - ./docker/superset_config.py:/app/pythonpath/superset_config.py

services:
  postgres:
    image: postgres:18
    container_name: postgres_container
    environment:
      POSTGRES_USER: user_psql
      POSTGRES_PASSWORD: pw_psql
      POSTGRES_DB: db_psql
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./postgres/initdb:/docker-entrypoint-initdb.d
    networks:
      - my-network
    ports:
      - "5432:5432"

  af:
    container_name: af_container
    image: apache/airflow:3.1.7
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow_db
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./api-request:/opt/airflow/api-request
      - /var/run/docker.sock:/var/run/docker.sock
    group_add:
      - '1000'  # Adiciona o grupo docker para permitir acesso ao socket
    depends_on:
      - postgres
    networks:
      - my-network
    command: >
      bash -c "airflow db migrate && airflow standalone"
    user: root

  dbt:
    container_name: dbt_container
    image: ghcr.io/dbt-labs/dbt-postgres:1.9.latest
    volumes:
      - ./dbt/my_project:/usr/app
      - ./dbt:/root/.dbt
    working_dir: /usr/app
    environment:
      DBT_PROFILES_DIR: "/root/.dbt"
    networks:
      - my-network
    depends_on:
      - postgres
    command: run

  superset:
    env_file:
      - path: docker/.env # default
        required: true
    image: apache/superset:3.0.0-py310
    command: ["/app/docker/docker-bootstrap.sh", "app"]
    restart: unless-stopped
    ports:
      - "8088:8088"
    user: *superset-user
    depends_on:
      superset-init:
        condition: service_completed_successfully
    volumes: *superset-volumes
    environment:
      DATABASE_DB: "superset_db"
    networks:
      - my-network

  superset-init:
    image: apache/superset:3.0.0-py310
    command: ["/app/docker/docker-init.sh"]
    env_file:
      - path: docker/.env # default
        required: true
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_started
    user: *superset-user
    volumes: *superset-volumes
    environment:
      DATABASE_DB: "superset_db"
      SUPERSET_LOAD_EXAMPLES: "no"
      SUPERSET_LOG_LEVEL: "${SUPERSET_LOG_LEVEL:-info}"
    healthcheck:
      disable: true
    networks:
      - my-network

  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "127.0.0.1:${REDIS_PORT:-6379}:6379"
    volumes:
      - redis:/data
    networks:
      - my-network
    

networks:
  my-network:
    driver: bridge

volumes:
  postgres_data:
  redis:
    external: false