version: 2

sources:
  - name: dev
    database: db_psql
    tables:
      - name: weather_data
        columns:
          - name: id
          - name: timestamp
          - name: ask
          - name: bid
          - name: mid
          - name: symbol